### ISSUE TITLE
增加阿里云云服务器

### ISSUE THREAD

**Issue by skoy03** [cnlancehu/qcip#3]
增加阿里云云服务器安全组放行IP支持

**Comment by cnlancehu** [comment]
后续会加，现在在重写

**Comment by skoy03** [comment]
回复得真快

**Comment by cnlancehu** [comment]
> 回复得真快

看邮箱就行，如果你有腾讯轻量服务器的话可以帮忙测试一下，大概寒假会开工

**Comment by skoy03** [comment]
有腾讯轻量云

**Comment by cnlancehu** [comment]
我暂时没腾讯轻量，加个联系方式吧，应该是要让你帮忙测试了

**Comment by skoy03** [comment]
1069367258

**Comment by skoy03** [comment]
> 我暂时没腾讯轻量，加个联系方式吧，应该是要让你帮忙测试了

QQ:1069367258

**Comment by cnlancehu** [comment]
你加我吧
2124757129
![Screenshot_2024-12-15-09-15-48-188_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/d63374f6-6fc2-4f4d-951c-591014c1e8bd)
